"""Generate the frozen M8-entry headline tables and the one retained benchmark figure."""
from pathlib import Path
import csv, json

ROOT=Path(__file__).parents[1]
OUT=ROOT/"research"/"m8_entry"

def main():
    OUT.mkdir(parents=True,exist_ok=True)
    m75=json.loads((ROOT/"experiments"/"m75"/"runs"/"summary.json").read_text())
    table=f"""# Frozen M8 Entry Scientific Tables

Generated by `scripts/build_m8_science.py`. Values are copied from committed milestone artifacts; they are not recomputed claims.

## Core validation — M1–M3

| Evidence | Result |
|---|---:|
| M1 historical tests | 65 passed |
| M3 fixed-input differential cases | 500/500 agreement |
| M3 frozen benchmark status agreement | 12/12 |

## Robustness — M4

| Mechanism/scenario | Profitable share |
|---|---:|
| Scholarship hard cutoff, B0 | 0.515625 |
| Registered phase-out, B0 | 0 |
| Exact weighted scholarship population | 0.9 |

## Strategic interaction — M5

| Quantity | Result |
|---|---|
| Neutral isolated manipulation gain | -2 |
| Gain against manipulating rival | +2 |
| Pure equilibria | (H,H), (M,M) |

## Repair regression — M6

| Evidence | Result |
|---|---|
| Candidates / regression checks / mutations | 74 / 351 / 245 |
| Deliberately coupled repair | REPAIR_INDUCED_VULNERABILITY; REPAIR_FAIL |
| Passing scholarship phase-outs in declared domains | 4 |

## External benchmark — M7

| Evidence | Result |
|---|---:|
| Cases | 30 |
| Historical rediscovery | 5/6 |
| Positive holdouts | 4/4 |
| Holdout negative findings | 0/2 |
| Negative controls clean | 10/10 |
| Boundary detections / evaluations | 19 / 369 |
| Combined detections / evaluations | 19 / 1,261 |

## M7.5 supplement

| Evidence | Result |
|---|---:|
| B5 supported / total | {m75['m7_b5']['supported']}/{m75['m7_b5']['total']} |
| B5 violated / satisfied / unsupported | {m75['m7_b5']['violated']} / {m75['m7_b5']['satisfied']} / {m75['m7_b5']['unsupported']} |
| B5 ground-truth agreement on supported cases | {m75['m7_b5']['ground_truth_agreements']}/{m75['m7_b5']['supported']} |
| B5 combined-search agreement on supported cases | {m75['m7_b5']['combined_agreements']}/{m75['m7_b5']['supported']} |
| Non-threshold stress status agreement | {m75['stress_status_agreements']}/{m75['stress_case_count']} |
"""
    (OUT/"HEADLINE_TABLES.md").write_text(table,encoding="utf-8")

    methods=[("Random",19,1204),("Grid",19,1061),("Boundary",19,369),("Exhaustive",18,1813),("Combined",19,1261)]
    width,height=820,360; left=145; scale=0.32
    bars=[]
    for index,(name,detected,evaluations) in enumerate(methods):
        y=55+index*55; w=evaluations*scale
        bars.append(f'<text x="15" y="{y+18}" font-size="15">{name}</text><rect x="{left}" y="{y}" width="{w:.1f}" height="25" fill="#3465a4"/><text x="{left+w+8:.1f}" y="{y+18}" font-size="14">{evaluations} evals; {detected} cases</text>')
    svg=f'''<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">
<rect width="100%" height="100%" fill="white"/><text x="15" y="28" font-size="20" font-weight="bold">IF-Bench v0.1: detections and candidate evaluations</text>
{''.join(bars)}<text x="15" y="345" font-size="12">Equal 100-evaluation per-case budgets. SMT-only omitted: solver time is not candidate-evaluation count.</text></svg>'''
    (OUT/"if_bench_method_comparison.svg").write_text(svg,encoding="utf-8")
    boxes=[("IncentiveSpec",310,25),("Reference Evaluator",280,105),("Search",25,205),("SMT Verify",175,205),("Population",335,205),("Finite Games",495,205),("Repair",655,205),("IF-Bench / Regression",280,305)]
    box_svg=[]
    for label,x,y in boxes: box_svg.append(f'<rect x="{x}" y="{y}" width="150" height="42" rx="5" fill="#f6f8fa" stroke="#244a73"/><text x="{x+75}" y="{y+26}" text-anchor="middle" font-size="14">{label}</text>')
    lines=['<path d="M385 67 V105"/>','<path d="M355 147 L100 205"/>','<path d="M370 147 L250 205"/>','<path d="M385 147 L410 205"/>','<path d="M400 147 L570 205"/>','<path d="M415 147 L730 205"/>','<path d="M100 247 L330 305"/>','<path d="M250 247 L355 305"/>','<path d="M410 247 L385 305"/>','<path d="M570 247 L415 305"/>','<path d="M730 247 L440 305"/>']
    architecture=f'''<svg xmlns="http://www.w3.org/2000/svg" width="830" height="380" viewBox="0 0 830 380"><rect width="100%" height="100%" fill="white"/><style>path{{stroke:#66788a;stroke-width:2;fill:none}}</style><text x="20" y="18" font-size="16" font-weight="bold">Incentive Fuzzer evidence architecture</text>{''.join(lines)}{''.join(box_svg)}<text x="415" y="370" text-anchor="middle" font-size="12">Every claim remains scoped to declared rules, properties, domains, actions, and assumptions.</text></svg>'''
    (OUT/"architecture.svg").write_text(architecture,encoding="utf-8")
    (OUT/"FIGURES.md").write_text("# Frozen M8 Entry Figures\n\nTwo generated figures are retained. `architecture.svg` presents the evidence flow without adding scientific claims. `if_bench_method_comparison.svg` makes the binding boundary-only result visible. The benchmark figure intentionally excludes SMT-only from the evaluation-count axis because solver work is not conceptually comparable to candidate evaluations.\n",encoding="utf-8")
    print("generated headline tables and 2 scientific figures")

if __name__=="__main__": main()
